Exploring and learning Neural Network fundamentals utilizing the PyTorch Tutorials through Pytorch.org.

<h2>Tensors</h2>

In [1]:
#Standard Imports
import torch
import numpy as np

<h3>Tensors Introduction</h3><p>Specialized data structure similiar to arrays. Used for encoding inputs and outputs of a model.</p>

In [19]:
#Initilize from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(f"Data:  \n{x_data}\n")

#Initilize from NumPy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"NumpPy:  \n{x_np}\n")

#Initilize from another tensor
x_ones = torch.ones_like(x_data) # retains datatype
print(f"Ones Tensor: \n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides datatype
print(f"Random Tensor: \n{x_rand}\n")


Data:  
tensor([[1, 2],
        [3, 4]])

NumpPy:  
tensor([[1, 2],
        [3, 4]])

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor: 
tensor([[0.2876, 0.3068],
        [0.7444, 0.2726]])



<h3>Tensor Operations</h3>

In [ ]:
#NumPy-like indexing + slicing
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [22]:
#Concatenate Tensors
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
#Arithmetic Operations

#Matrix Multiplication (y1, y2, y3 all equivalent)
y1 = tensor @ tensor.T #tensor.T returns transpose of tensor
y2 = tensor.matmul(tensor.T)

y3= torch.rand_like(y1) #random tensor with shape of y1
torch.matmul(tensor,tensor.T,out=y3) #y3 stores result of dot product

#Element-wise product (z1, z2, z3 all equivalent)
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor) #random tensor with shape of z1
z3 = torch.mul(tensor,tensor,out=z3) #z3 stores result of element-wise product

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
#Single element tensor and conversion
agg = tensor.sum() # aggregating all values of a tensor
agg_item = agg.item()
print(agg, type(agg)) # Single-element
print(agg_item, type(agg_item))# Converted

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


<h3>Bridging with NumPy</h3>
<p>Tensors on the CPU (as opposed to on an accelorator) can share memory locations with NumPy arrays.</p>

In [34]:
#Tensor to NumPy
t = torch.ones(5) #array of five 1s
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

#changing one changes both
t.add_(1) #_ denotes in-place operation that stores result into operand, discouraged 
print("value added: 1")
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
value added: 1
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [37]:
#Numpy to  Tensor
n = np.ones(5)
t= torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

np.add(n,1,out=n)
print("value added: 1")
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]
value added: 1
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
